### ISSUE TITLE
Content div on index.html not big enough. Causes display error. 

### ISSUE THREAD

**Issue by jstockwin** [robin-thompson/robin-thompson.github.io#2]
Content does not take into account the image, which has a height of 600px. The height of the content div is much smaller than this - it fits the text only. This causes the footer to be half way up the page if you are zoomed in enough. See below. 

<img width="320" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/8227759/12071230/73160be0-b098-11e5-8a45-eb745210251f.png">

**Comment by jstockwin** [comment]
Going to wrap everything in a 600px div for now until there is enough content on the page to resolve the issue.

**Comment by Tom-Johnston** [comment]
Try setting the div to overflow:hidden.

**Comment by jstockwin** [comment]
Thanks @Tom-Johnston
